### ISSUE TITLE
Little explanation for function fmt at Document

### ISSUE THREAD

**Issue by thewilly** [weso/utils#12]
Hi, could you please provide me some information about what this function functionality is ?

https://github.com/weso/utils/blob/9cbf59aff2f34fbaa9bcd6abf7b7db5bb43c1767/modules/utils/src/main/scala/es/weso/document/Document.scala#L66-L93

**Comment by labra** [comment]
As it says at the beginning of the file, that code was originally part of Scala's standard library. 

However, at scala 2.11 (I think) it was separated from the standard library and marked as deprecated.

Nevertheless, the code is useful when one wants to pretty print some language and that's why several projects embed the code directly in their code base. 

It would probably be better to have a standalone repository and library for the code, but as it is so simple, no one is doing it AFAIK. 

At this moment, I am not sure iff that particular function is being invoked and could probably be removed. 

For some background about that code, I think [this paper](https://lindig.github.io/papers/strictly-pretty-2000.pdf) by C. Lindig contains an explanation of pretty printing in general.

**Comment by thewilly** [comment]
API moved to https://github.com/weso/document
